version: "3"

services:
  db:
    container_name: auth_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : auth_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: auth_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL : postgres@auth.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - db